version: '3'
services:
  nginx:
    image: babish/nginx:latest
    ports:
     - "${APP_PORT}:80"
    volumes:
     - ./www:/var/www/html
    networks:
     - appnet
  php:
    image: babish/php:latest
    volumes:
     - ./www:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "${PHPMYADMIN_PORT}:80"
      environment:
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      depends_on:
        - db
      restart: always
      networks:
           - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
